spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AmitK2204/ConfigData
server:
  port: 8001
  error:
    include-exception: true
    whitelabel:
      enabled: false
    include-stacktrace: always  